### ISSUE TITLE
Running the Project

### ISSUE THREAD

**Issue by ilyes495** [ntamas/cl1#10]
Thank you so much for this valuable project, I have been trying to run the project for a couple days, but I couldn't figure out how to do it, since I have less experience with java projects. I hope someone can explain how I can get the project compiled and running. I have gone through the command line folder, it says to run a command with a jar file, but I can't find it anywhere. 
Thank you so much

**Comment by ntamas** [comment]
The JAR file is the compiled, executable version of the software. You can download a pre-compiled version from [here][1]. Alternatively, you can download the software on your own:

1. Get the [Java SE Development Kit (JDK)][3].
2. Download [Apache Ant][2], the build tool that will compile the project with the Java compiler.
3. From the root folder of the source code, run `ant build` - this will create the JAR file for you.

Considering that you have less experience with Java projects, I suggest you try the precompiled JAR first.

  [1]: http://www.paccanarolab.org/cluster-one/
  [2]: https://ant.apache.org/
  [3]: http://www.oracle.com/technetwork/java/javase/downloads/index-jsp-138363.html

**Comment by ilyes495** [comment]
Thank you so much, it worked
