### ISSUE TITLE
multithreaded execution

### ISSUE THREAD

**Issue by angel-bee2018** [ntamas/cl1#13]
Hi! 

I was wondering how to make ClusterONE run in parallel for multiple cores? I noticed that a recent bug fix pertained to multithreaded execution, but there seems to be no official documentation on how to do that. Is it for the command line version only? Or is it available in the cytoscape version too?

Any help would be appreciated :)

**Comment by ntamas** [comment]
The command line version has a `--num-threads` switch (from version 1.1 onwards) that you can use to set how many threads you want the app to use. The Cytoscape plugin does not have this functionality; I am not in academia any more so the Cytoscape plugin went unmaintained a few years ago, and as far as I know it's not compatible with newer versions anyway.

_Edit_: the default value of `--num-threads` is `auto`, which sets a reasonable value based on the number of CPU cores, so if you are using version 1.1 or 1.2, then there is not much point in tweaking `--num-threads`.

**Comment by angel-bee2018** [comment]
thanks! :) I did not know it was unmaintained because it still works in the older version of cytoscape i got
