### ISSUE TITLE
Extract selected clusters as subnetworks in Cytoscape doesn't work

### ISSUE THREAD

**Issue by srikanthBezawada** [ntamas/cl1#8]
Has this option(_Extract selected clusters_)  worked for you before ?

Simple fix would be changing this..

NewNetworkSelectedNodesAndEdgesTaskFactory taskFactory = this.resultViewer.getCytoscapeApp().getService(CySwingAppAdapter.class).get_NewNetworkSelectedNodesAndEdgesTaskFactory();

I've tested this, Shall I send a PR ?

**Comment by ntamas** [comment]
It definitely worked in Cytoscape 2.x back in the old days; I don't know whether it was tested with Cytoscape 3.x ;) Please send a PR - I am on holiday at the moment but I'll review it when I'm back.

**Comment by srikanthBezawada** [comment]
Sent PR for this issue,

Please ignore my previous PR [https://github.com/ntamas/cl1/pull/7](url) , 
And thanks for the results panel design :)

**Comment by ntamas** [comment]
Closing this; discussion will continue in PR #9.
